# Generated by Django 4.1.4 on 2023-03-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('sauces', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('image_1', models.ImageField(upload_to='images/food/')),
                ('image_2', models.ImageField(upload_to='images/food/')),
                ('image_3', models.ImageField(upload_to='images/food/')),
                ('image_4', models.ImageField(upload_to='images/food/')),
            ],
        ),
    ]
