# Generated by Django 4.1.4 on 2023-01-04 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=uuid.uuid4, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image_1', models.ImageField(upload_to='images/food/')),
                ('image_2', models.ImageField(upload_to='images/food/')),
                ('image_3', models.ImageField(upload_to='images/food/')),
                ('image_4', models.ImageField(upload_to='images/food/')),
                ('sauces_available', models.CharField(choices=[('Tomato Ketchup', 'Tomato Ketchup'), ('Peri Peri Mayo', 'Peri Peri Mayo'), ('Shito', 'Shito'), ('Honey Mustard Mayo', 'Honey Mustard Mayo'), ('Mango Mayo', 'Mango Mayo'), ('Only The Brave Hot Sauce', 'Only The Brave Hot Sauce'), ('Shata Mayonnaisse', 'Shata Mayonnaisse')], default='Tomato Ketchup', max_length=40)),
            ],
        ),
    ]
