# Generated by Django 4.1.4 on 2023-02-13 02:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=uuid.uuid4, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('sauces', models.CharField(max_length=100)),
                ('image_1', models.ImageField(upload_to='images/food/')),
                ('image_2', models.ImageField(upload_to='images/food/')),
                ('image_3', models.ImageField(upload_to='images/food/')),
                ('image_4', models.ImageField(upload_to='images/food/')),
            ],
        ),
    ]
